PERIPHERALS = pwm pit spi
DRIVERS = usb_serial panic nrf24
SRC = racer.c motors.c radio.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer
include ../libs/libs.mk
include ../../boards/board.mk

