PERIPHERALS = pwm pit
DRIVERS = usb_serial panic
SRC = racer.c motors.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer
include ../libs/libs.mk
include ../../boards/board.mk

