#ifndef HAYDEN_OG_H
#define HAYDEN_OG_H

#include "pitches.h"
#include "durations.h"
#include "stdint.h"

#define SONG_BPM 132
#define NOTE_DIVIDER 8
#define SONG_NOTE_CHANGE_PER_MIN SONG_BPM * NOTE_DIVIDER // eg 1/8th notes per min
// #define SONG_MS_PER_NOTE 60000 / SONG_NOTE_CHANGE_PER_MIN // eg x ms per 1/8th note duration
#define SONG_MS_PER_NOTE 78 //57 for scoooby dooo

#define NUM_NOTES 33


// const uint32_t notes[NUM_NOTES] = {
//     NOTE_E4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_G4, NOTE_E4, NOTE_E4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_G4,
//     NOTE_E4, NOTE_D4, NOTE_E4, NOTE_D4, NOTE_C4, NOTE_REST, NOTE_E4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_G4,
//     NOTE_E4, NOTE_E4, NOTE_G4, NOTE_A4, NOTE_B4, NOTE_G4, NOTE_E4, NOTE_D4, NOTE_E4, NOTE_D4, NOTE_C4
// };

// const uint8_t durations[NUM_NOTES] = {
//     DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER,
//     DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_HALF,
//     DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_EIGHTH,
//     DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER,
//     DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_QUARTER, DURATION_HALF
// };

#endif  