PERIPHERALS = pit systick
DRIVERS = pacer usb_serial adxl345 panic piezo
SRC = hat.c accelerometer.c scheduler.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
